AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ScratchFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: scratch.handler
      Runtime: nodejs6.10
      FunctionName: ScratchFunction
      Environment:
        Variables:
          ECHO_PHRASE: hello world
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /scratch
            Method: get
  TicketGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: tickets-get.handler
      Runtime: nodejs6.10
      FunctionName: TicketGetFunction
      Policies:
        - AWSLambdaDynamoDBExecutionRole #managed policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
                - dynamodb:GetItem
              Resource: !GetAtt DynamoDBTicketTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTicketTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /ticket
            Method: get
  TicketPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: tickets-post.handler
      Runtime: nodejs6.10
      FunctionName: TicketPostFunction
      Policies:
        - AWSLambdaDynamoDBExecutionRole #managed policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt DynamoDBTicketTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTicketTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /ticket
            Method: post
  DynamoDBTicketTable:
   Type: AWS::DynamoDB::Table
   Properties:
     TableName: SXRTickets
     AttributeDefinitions:
       - AttributeName: id
         AttributeType: S
     KeySchema:
       - AttributeName: id
         KeyType: HASH
     ProvisionedThroughput:
       ReadCapacityUnits: 5
       WriteCapacityUnits: 5