AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DynamoDBTicketTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: SXRTickets
    Type: AWS::DynamoDB::Table
  ScratchFunction:
    Properties:
      CodeUri: s3://ticket-service-deployment/1721fcec10b2c3b45b7ecb31af3fcd55
      Environment:
        Variables:
          ECHO_PHRASE: hello world
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /scratch
          Type: Api
      FunctionName: ScratchFunction
      Handler: scratch.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  TicketGetFunction:
    Properties:
      CodeUri: s3://ticket-service-deployment/1721fcec10b2c3b45b7ecb31af3fcd55
      Environment:
        Variables:
          TABLE_NAME:
            Ref: DynamoDBTicketTable
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /ticket
          Type: Api
      FunctionName: TicketGetFunction
      Handler: tickets-get.handler
      Policies:
      - AWSLambdaDynamoDBExecutionRole
      - Statement:
        - Action:
          - dynamodb:Scan
          - dynamodb:GetItem
          Effect: Allow
          Resource:
            Fn::GetAtt:
            - DynamoDBTicketTable
            - Arn
        Version: '2012-10-17'
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  TicketPostFunction:
    Properties:
      CodeUri: s3://ticket-service-deployment/1721fcec10b2c3b45b7ecb31af3fcd55
      Environment:
        Variables:
          TABLE_NAME:
            Ref: DynamoDBTicketTable
      Events:
        GetResource:
          Properties:
            Method: post
            Path: /ticket
          Type: Api
      FunctionName: TicketPostFunction
      Handler: tickets-post.handler
      Policies:
      - AWSLambdaDynamoDBExecutionRole
      - Statement:
        - Action:
          - dynamodb:PutItem
          Effect: Allow
          Resource:
            Fn::GetAtt:
            - DynamoDBTicketTable
            - Arn
        Version: '2012-10-17'
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
